### ISSUE TITLE
issue open pyTorXy in neon 6.2

### ISSUE THREAD

**Issue by violantel** [kfx0/pytorxy#1]
Hi,
when I launch the console command:
bash "/home/user/pyTorXy/Python GUI/pytorxy.sh"
I get the following error:
Traceback (most recent call last):
  File "/home/user/pyTorXy/Python GUI/pytorxy.py", line 241, in <module>
    GUI = mainwindow(window);
          ^^^^^^^^^^^^^^^^^^
  File "/home/user/pyTorXy/Python GUI/pytorxy.py", line 92, in __init__
    img = ImageTk.PhotoImage(Image.open("logo_tor.png").resize((50, 50), Image.ANTIALIAS));
                                                                         ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

how can I solve this problem?

I solved the problem by replacing in file "/home/user/pyTorXy/Python GUI/pytorxy.py"
Image.ANTIALIAS with Image.Resampling.LANCZOS

now it works.
Thank you

**Comment by violantel** [comment]
I solved the problem by replacing in file "/home/user/pyTorXy/Python GUI/pytorxy.py"
Image.ANTIALIAS with Image.Resampling.LANCZOS

now it works. 
Thank you
